// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Winvent.Infrastructure.Data;

#nullable disable

namespace Winvent.Infrastructure.Migrations
{
    [DbContext(typeof(WinventDbContext))]
    [Migration("20231108184753_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Winvent.Domain.Models.Admin", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUserName")
                        .HasColumnType("TEXT");

                    b.HasKey("AdminId");

                    b.ToTable("MyProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
